
version: 2

build:
  os: ubuntu-22.04  # Auto-detect OS
  tools:
    python: "3.11"  # Auto-detect Python version

sphinx:
  configuration: source/conf.py

submodules:
  include: all

formats:
  - pdf
  - epub