
version: 2

build:
  os: ubuntu-22.04  # Auto-detect OS
  tools:
    python: "3.11"  # Auto-detect Python version
  jobs:
    pre_build:
      - apt-get install -y graphviz && apt-get install -y make  # Install system packages
    post_build:
      - echo "Build finished"
python:
  version: 3.9
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

sphinx:
  configuration: source/conf.py

submodules:
  include: true

formats:
  - pdf
  - epub