
version: 2

build:
  os: ubuntu-22.04  # Auto-detect OS
  tools:
    python: "3.11"  # Auto-detect Python version

sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: true
  
submodules:
  include: all

formats:
  - pdf
  - epub