
version: 2

build:
  os: ubuntu-22.04  # Auto-detect OS
  tools:
    python: "3.11"  # Auto-detect Python version

sphinx:
  configuration: source/conf.py
  extensions:
    - sphinx.ext.todo
    - sphinx.ext.viewcode
git:
  submodules:
    depth: 3

formats:
  - pdf
  - epub